In [2]:
import pandas as pd
import numpy as np

### Paso A

In [3]:

#Cargando los datos
costos_producion_df = pd.read_csv("db/Costos_producción.csv")
recursos_df = pd.read_csv("db/Recursos.csv")


In [4]:
#Muetro los datos de costos
costos_producion_df.head()

Unnamed: 0  Producto  Costo de producción
0           0        18              1676480
1           1        13              1635176
2           2         4              1764282
3           3        10              1695162
4           4        27              1804233

In [5]:
#muestro los datos de recursos
recursos_df.head()

Unnamed: 0  Tipo de recurso  Cantidad  Producto
0           0               32        50        36
1           1               40        76        32
2           2               49        68        47
3           3                6        70        10
4           4               20        68        32

In [6]:
#Veo como se compone un producto para entender como se relaciona esto
#Como grupo llegamos a la conclusion que si expresamos cada producto como un vector, el domineo seria los tipos recursos y cada coficiente seria la cantidad de ese recurso
#Por lo cual el valor de cada tipo recurso seria vector * x = costo del producto
recursos_df[recursos_df["Producto"] == 36]

Unnamed: 0  Tipo de recurso  Cantidad  Producto
0              0               32        50        36
28            28               29        68        36
117          117               36        57        36
137          137               23        78        36
190          190               48        68        36
244          244               38        75        36
359          359               28        49        36
436          436               45        43        36
470          470               12        73        36
520          520               10        50        36
559          559               24        48        36
560          560               34        76        36
706          706                1        74        36
843          843                6        76        36
989          989               42        74        36
1149        1149               22        70        36
1152        1152               41        45        36
1195        1195               46        48        36
1263        1263               37        79        36
1328        1328               33        77        36
1343        1343               25        51        36
1352        1352               40        48        36
1399        1399                9        43        36
1474        1474                2        64        36
1493        1493               13        65        36
1520        1520               39        64        36
1527        1527               50        45        36
1534        1534                4        59        36
1559        1559               15        48        36
1575        1575               14        60        36
1646        1646               44        62        36
1750        1750                7        79        36
1790        1790               16        79        36
1811        1811               11        60        36
1882        1882                3        67        36
1888        1888               49        60        36
1897        1897               31        62        36
1960        1960               19        41        36
1969        1969                5        44        36
2005        2005               17        43        36
2014        2014               47        48        36
2078        2078               30        78        36
2117        2117                8        55        36
2139        2139               21        69        36
2168        2168               35        55        36
2329        2329               27        71        36
2368        2368               20        57        36
2397        2397               43        61        36
2427        2427               18        67        36
2470        2470               26        45        36

### Paso B

In [44]:
#Cargo los productos para el i y la j con el tipo recurso
#Se utiliza la función unique , ya que un mismo producto puede utilzar disntintos tipos de recursos. Por ende habrá una repetición y esta función permite esclarecer la totalidad sin considerar lo anterior
#El unique utilizado sobre el tipo de recurso, permite identificar en unicidad los tipos existentes, debido a que pueden haber productos que usen el mismo tipo de recurso en su producción y saldrían repetidos. 
i = np.sort(np.array(recursos_df["Producto"].unique()))
j = np.sort(np.array(recursos_df["Tipo de recurso"].unique()))

matriz_A = np.zeros((len(i), len(i)), dtype="int")
matriz_A

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

La matrix en i son los productos y la j o sea las columnas son los tipo recursos, pues asi es un matrix cuadrada

In [46]:
j

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [47]:
for _, fila in recursos_df.iterrows():
    p = fila["Producto"]
    c = fila["Tipo de recurso"]
    x = np.where(i == p)
    y = np.where(j == c)
    matriz_A[x, y] = fila["Cantidad"]

In [48]:
matriz_A

array([[60, 54, 76, ..., 51, 70, 73],
       [41, 60, 45, ..., 50, 75, 45],
       [55, 50, 72, ..., 64, 72, 78],
       ...,
       [50, 69, 69, ..., 41, 64, 72],
       [66, 52, 77, ..., 61, 50, 49],
       [61, 43, 48, ..., 58, 78, 60]])

### Paso C

In [54]:
#Como las filas (i) son numero de producto, debemos ordenar los costos para que valor concida con el producto en la fila de la matriz
costos_producion_df = costos_producion_df.sort_values(by="Producto")


### Pregunta D

In [55]:
#Creo el vector de cosotos y como lo ordenamos antes la fila uno de la matriz conincidira con el cosoto del producto uno, y asi sucesivmente
vector_costos = np.array(costos_producion_df["Costo de producción"])
vector_costos

array([1752625, 1719304, 1837615, 1764282, 1742108, 1792307, 1759963,
       1780502, 1808398, 1695162, 1779912, 1778551, 1635176, 1793300,
       1832280, 1831478, 1777934, 1676480, 1817541, 1653958, 1853507,
       1659497, 1697236, 1700697, 1739332, 1828149, 1804233, 1698686,
       1830959, 1694014, 1826130, 1771014, 1779345, 1729440, 1812504,
       1816633, 1746407, 1802411, 1832598, 1778015, 1764231, 1777600,
       1788152, 1875284, 1743951, 1833116, 1782662, 1801560, 1828692,
       1706024])

In [56]:
# la solucuon del sistema de A*x=b en donde A es la matriz que hicimos y b el vector de costos, da como resultado que x es lo que cuesta cada tipo de material
solucion = np.linalg.solve(matriz_A, vector_costos)
print(solucion)

[272. 895. 722. 329. 142. 900. 191. 819. 314. 744. 492. 534. 863. 535.
 982. 930. 563. 801. 876. 159. 760. 645. 619. 154. 684. 187. 293. 255.
 853. 936. 549. 773. 603. 158. 226. 768. 859. 250. 825. 538. 401. 734.
 322. 290. 764. 925. 951. 908. 919. 502.]


### Paso E

In [7]:
recursos_new_df = pd.read_csv("db/Recursos_new.csv")

In [67]:
i_new = np.sort(np.array(recursos_new_df["Producto"].unique()))
j_new = np.sort(np.array(recursos_new_df["Tipo de recurso"].unique()))

matriz_B = np.zeros((len(i_new), len(j_new)), dtype="int")

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [73]:
#Ordenamos para que al hacer el bucle la fila del dataframe calce con la i del la matriz_B
recursos_new_df = recursos_new_df.sort_values(by="Producto")

In [75]:
for _, fila in recursos_new_df.iterrows():
    p = fila["Producto"]
    c = fila["Tipo de recurso"]
    x = np.where(i_new == p)
    y = np.where(j_new == c)
    matriz_B[x, y] = fila["Cantidad"]

matriz_B

array([[58, 42, 99, ..., 58, 24, 19],
       [22,  2,  1, ...,  6, 65, 77],
       [49, 64, 89, ...,  4, 88, 13],
       ...,
       [69, 79, 33, ..., 99, 26, 89],
       [91, 66, 62, ..., 40, 95, 78],
       [75, 11, 62, ..., 45, 87, 93]])

### Paso F

In [76]:
resultado = matriz_B @ solucion

In [77]:
resultado

array([1307969., 1369888., 1370090., 1452950., 1438681., 1531656.,
       1557838., 1552567., 1700447., 1413942., 1401654., 1544681.,
       1458089., 1367960., 1320189., 1705280., 1671250., 1526545.,
       1643002., 1379702., 1222902., 1307655., 1543348., 1291802.,
       1295451., 1579620., 1528197., 1547984., 1580750., 1409813.,
       1593583., 1341882., 1328397., 1568469., 1589261., 1511813.,
       1313978., 1582668., 1598587., 1670011., 1450969., 1429081.,
       1555316., 1617432., 1643200., 1324313., 1277901., 1495095.,
       1493810., 1438160.])

### Pregunta G

Si se tuvieran 40 productos antiguos, la matriz sería de 40x50, luego  el sistema asociado a esa matriz seria uno de 40 ecuaciones y 50 incógnitas. Esto también se puede entender como un transformacion lineal de R50 -> R40, y por Teorema núcleo imagen 50 = Dim(Null) + Dim(Im), la dimension de la imagen como máximo es 40 por lo que, el null siempre será mayor a 0 significando que  no existe solucion única y no se podría obtener todos los precios de cada tipo de recurso pues alguno quedarian independientes.

### Pregunta H

No sería necesario pues con los 50 ya se puede tener la solucion única, debido a que según el Teorema del núcleo imagen el Null es 0 y se pueden obtener todos los precios.  Adicionalmente en el caso de tener más productos puede darse el caso que un producto sea muy antiguo, lo que puede hacer que un producto tenga diferentes precios en los **Tipo de recurso* ;  ejemplo un queso1 que la leche costaba $500 y un queso2 que costaba $700, lo que provocaría que el sistema no tuviera solucion. Finalmente obtener una mayor cantidad de información de otro momento, podría servir en otro contexto donde se requirirera una comparativa temporal entre las variables, pero incluso en este hipotético si estuvieran en el mismo archivo deberían tener una etiqueta con su tiempo respectivo.